source 'https://rubygems.org'

ruby '2.4.1'

# Basics
gem 'rails'
gem 'pg'
gem 'puma'

# Auth
# gem 'devise'
# gem 'omniauth-facebook'

# Asset Management
# gem 'aws-sdk'
# gem 'mini_magick'

# Monitoring
gem 'newrelic_rpm'
gem 'sentry-raven'

# Frontend Common
gem 'webpacker', github: 'rails/webpacker'

# Admin
gem 'bootstrap_form'
gem 'kaminari'
gem 'haml'

gem 'parallel', require: false

# gem 'sidekiq'
# gem 'sinatra', require: nil

group :production, :staging do
  gem 'puma_worker_killer'
  gem 'rails_12factor'
  gem 'dalli'
end

group :development do
  gem 'web-console'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rubocop'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'pry-rails'
  gem 'dotenv-rails'
  gem 'fabrication'
  gem 'ffaker'
  gem 'fuubar'

  gem 'bullet'
  gem 'bundler-audit', '>= 0.5.0', require: false
end

group :test do
  gem 'timecop'
  gem 'webmock'
  gem 'database_cleaner'
end
