default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: <%= ENV['DB_POOL_SIZE'] || ENV['MAX_THREADS'] || 10 %>
  reaping_frequency: <%= ENV['DB_REAPING_FREQUENCY'] || 10 %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: <%= !ENV['NO_PREPARED_STATEMENTS'] %>
  advisory_locks: <%= !ENV['NO_ADVISORY_LOCKS'] %>

development: *default

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

production: *default
staging: *default
